# This configuration file contains all options for the vulkan-renderer.
# Do not change any values unless you know exactly what you are doing!

title = "vulkan-renderer-configuration"

#TODO: Declare further TOML configuration files here?

[application]
name = "Inexor-Application"

[application.engine]
name = "Inexor-Engine"

[application.window]
mode = "windowed"
width = 800
height = 800
name = "Inexor-Vulkan-Renderer"

[shaders]
[shaders.gltf.vertex]
files = [
	"shaders/gltf/mesh.vert.spv",
]

[shaders.octree.vertex]
files = [
	"shaders/octree/main.vert.spv",
]

[shaders.imgui.vertex]
files = [
	"shaders/imgui/main.vert.spv",
]

[shaders.gltf.fragment]
files = [
	"shaders/gltf/mesh.frag.spv",
]

[shaders.octree.fragment]
files = [
	"shaders/octree/main.frag.spv",
]

[shaders.imgui.fragment]
files = [
	"shaders/imgui/main.frag.spv",
]

# TODO: Use key/value pairs and give textures user friendly names.
[textures]
files = [
	"assets/textures/texture_A_1024.jpg",
	"assets/textures/texture_B_1024.jpg",
	"assets/textures/texture_C_1024.jpg",
	"assets/textures/texture_D_1024.jpg",
	"assets/textures/texture_E_1024.jpg",
	"assets/textures/texture_F_1024.jpg",
	"assets/textures/texture_G_1024.jpg",
	"assets/textures/logo_rendered.png",
]

# glTF 2.0 is the new standard 3D model format.
# https://www.khronos.org/gltf/
[gltfmodels]
files = [
	"assets/models/inexor/glTF-Binary/ToyCar.glb",
]
