# This configuration file contains all options for the vulkan-renderer.
# Do not change any values unless you know exactly what you are doing!

title = "vulkan-renderer-configuration"

#TODO: Declare further TOML configuration files here?

[application]
name = "Inexor-Application"

[application.version]
major = 1
minor = 0
patch = 0

[application.engine]
name = "Inexor-Engine"

[application.engine.version]
major = 1
minor = 0
patch = 0

[application.window]
width = 800
height = 600
name = "Inexor-Vulkan-Renderer"

[shaders]
[shaders.vertex]
files = [
	"shaders/vertexshader.spv",
]

[shaders.fragment]
files = [
	"shaders/fragmentshader.spv",
]

# TODO: Use key/value pairs and give textures user friendly names.
[textures]
files = [
	"assets/textures/texture_A_1024.jpg",
	"assets/textures/texture_B_1024.jpg",
	"assets/textures/texture_C_1024.jpg",
	"assets/textures/texture_D_1024.jpg",
	"assets/textures/texture_E_1024.jpg",
	"assets/textures/texture_F_1024.jpg",
	"assets/textures/texture_G_1024.jpg",
	"assets/textures/logo_rendered.png",
]

# glTF 2.0 is the new standard 3D model format.
# https://www.khronos.org/gltf/
[glTFmodels]
files = [
	"assets/models/inexor-logo/inexor_logo.gltf",
]
